version: '2'

services:
  server:
    build: ./.docker/nginx
    image: boxalino/rtux-nginx:1.15
    container_name: boxalino_rtux_nginx
    volumes:
      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/conf/sites-enabled:/usr/local/bin/nginx/sites-enabled
      - ./.docker/nginx/logs:/var/log/nginx
    volumes_from:
      - code
    ports:
      - 80
      - 443
    links:
      - php
    tty: true
    environment:
      SERVER_NAME: "rtux.boxalino.work"
    env_file:
      - ./.docker/nginx/.env
      - ./.env

  php:
    build: ./.docker/php
    image: boxalino/rtux-php:7.2
    container_name: boxalino_work_rtux_php7.2
    volumes_from:
      - code
    volumes:
      - ./.docker/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/logs:/var/log/php
    ports:
      - 9000
    links:
      - code
    environment:
      PHP_IDE_CONFIG: "serverName=rtux.boxalino.work"

  app:
    build: ./.docker/cli
    image: boxalino/rtux-cli:7.2
    container_name: boxalino_rtux_cli
    links:
      - code
    volumes_from:
      - code
    volumes:
      - ./.docker/cli/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
    environment:
      PROJECT_ROOT: "/var/www/app"
    env_file:
      - ./.env

  code:
    build: ./.docker/volume
    image: boxalino/rtux-volume
    container_name: boxalino_rtux_volume
    volumes:
      - ./code:/var/www/app
    environment:
      SETUP_VOLUME: "/var/www/app"
