version: '2'

services:
  app:
    build: ./.docker/php
    image: boxalino/rtux-app-php:7.2
    container_name: boxalino_rtux_api_app_php7.2
    volumes_from:
      - app-code
    volumes:
      - ./.docker/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/logs:/var/log/php
    ports:
      - 8000
    links:
      - app-code
    env_file:
      - ./.env

  cli-setup:
    build: ./.docker/cli
    image: boxalino/rtux-api-cli:7.2
    container_name: boxalino_rtux_api_cli
    links:
      - app-code
    volumes_from:
      - app-code
    volumes:
      - ./.docker/cli/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
    environment:
      PROJECT_ROOT: "/var/www/app"
    env_file:
      - ./.env

  app-code:
    build: ./.docker/volume
    image: boxalino/rtux-volume
    container_name: boxalino_rtux_volume
    volumes:
      - .:/var/www/app
    environment:
      SETUP_VOLUME: "/var/www/app"
